"""Configuración pública y no sensible del proyecto."""

from __future__ import annotations

APP_NAME = "OCR Documental Web"
APP_VERSION = "0.5.0"
PROJECT_PHASE = "Fase 5"
MOCK_MODE = False
GEMINI_ENABLED = False

GOOGLE_DATABASE_FILE_NAME = "OCR_DOCUMENTAL_DB"
GOOGLE_DATABASE_APP_PROPERTY_KEY = "ocr_role"
GOOGLE_DATABASE_APP_PROPERTY_VALUE = "database"

DRIVE_INPUT_FOLDER_NAME = "OCR_ENTRADA"
DRIVE_CONFIRMED_FOLDER_NAME = "OCR_CONFIRMADOS"
DRIVE_FOLDER_MIME_TYPE = "application/vnd.google-apps.folder"

MAX_FILES_PER_UPLOAD = 10
MAX_FILE_SIZE_MB = 20
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
MAX_PDF_PAGES = 200
VISUAL_DUPLICATE_MAX_DISTANCE = 6

OCR_LANGUAGE = "es"
OCR_VERSION = "PP-OCRv6"
OCR_PRIMARY_DETECTION_MODEL = "PP-OCRv6_tiny_det"
OCR_PRIMARY_RECOGNITION_MODEL = "PP-OCRv6_tiny_rec"
OCR_FALLBACK_VERSION = "PP-OCRv5"
OCR_FALLBACK_DETECTION_MODEL = "PP-OCRv5_mobile_det"
OCR_FALLBACK_RECOGNITION_MODEL = "latin_PP-OCRv5_mobile_rec"
OCR_CPU_THREADS = 2
OCR_TARGET_LONG_SIDE = 2000
OCR_MIN_SCORE = 0.35
OCR_RECOVERY_SCORE = 0.75
OCR_LOCK_MINUTES = 30
OCR_LONG_RECEIPT_RATIO = 2.5
OCR_SEGMENT_OVERLAP = 160
SHEET_JSON_PLAIN_LIMIT = 45_000

CANDIDATE_WEIGHTS = {
    "ocr": 0.35,
    "format": 0.25,
    "label": 0.20,
    "position": 0.10,
    "consistency": 0.10,
}
CONFIDENCE_RELIABLE = 0.90
CONFIDENCE_REVIEW = 0.75
CANDIDATE_CONFLICT_DELTA = 0.05
MONETARY_TOLERANCE = "0.02"
REASONABLE_MIN_YEAR = 2000
REASONABLE_MAX_FUTURE_YEARS = 1
PEAJE_REQUIRED_FIELDS = ("lugar", "fecha", "placa", "monto_total")
PERUVIAN_PLATE_MASKS = ("LLLDDD", "LDLDDD", "LLDDDD")

ALLOWED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".pdf"}
ALLOWED_MIME_TYPES = {
    "image/jpeg",
    "image/png",
    "image/webp",
    "application/pdf",
}
